[[hftctp_lib]]
arch = "x86_64"
git-tree-sha1 = "4112e60f4f225c2371a172c880c97185b4d41e75"
os = "windows"

    [[hftctp_lib.download]]
    sha256 = "815a88d8c16ef7a80365c8567ab418f1a81492e0fb101389e13d86647170fba4"
    url = "https://github.com/linanisyugioh/HFTCTP.jl/releases/download/V1.0.0/hftctp_windows_x64.tar.gz"
[[hftctp_lib]]
arch = "x86_64"
git-tree-sha1 = "4112e60f4f225c2371a172c880c97185b4d41e75"
libc = "glibc"
os = "linux"

    [[hftctp_lib.download]]
    sha256 = "3358dda8d69c5cde9984e92921e29fabcd947ce1899f487bad1dc918eb9563b9"
    url = "https://github.com/linanisyugioh/HFTCTP.jl/releases/download/V1.0.0/hftctp_linux_x64.tar.gz"
